name: Server Test

on:
  pull_request:
    branches: [ master ]
    paths:
      - "server/**"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
        working-directory: server
      - run: yarn test
        working-directory: server